add and fix all return code of current function

diff --git a/iptables b/iptables
--- a/iptables
+++ b/iptables
@@ -32,23 +32,8 @@
 VERSION='3.0'
 #==============================================================================
 
-### BEGIN INIT INFO
-# Provides:          iptables
-# Required-Start:	   $syslog $network
-# Required-Stop:	   $syslog $network
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Configure rules for iptables firewall
-# Description:       This script define rules for the iptables firewall
-### END INIT INFO
-
 #========== INTERNAL OPTIONS ==========#
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DESC="Firewall service"
-NAME=iptables
-SCRIPTNAME=/etc/init.d/$NAME
-
-IPTABLES=$(which iptables)
+IPTABLES="dump"
 IP6TABLES=$(which ip6tables)
 #IPTABLES_CONFIG=/etc/default/$NAME
 IPTABLES_CONFIG=./config
@@ -99,11 +84,24 @@ E_REG_DST='(d|dst)'
 
 #========== INTERNAL FUNCTIONS ==========#
 
+function dump() {
+  return
+}
+
+
 # Print a msg to stdout if verbose option is set
 # @param[string] : the msg to write in stdout
 function _echo() {
   if [ $IS_VERBOSE -eq 1 ]; then
     echo -e "$@"
+  fi
+}
+
+# Print a msg to stderr if verbose option is set
+# @param[string] : the msg to write in stderr
+function _error() {
+  if [ $IS_VERBOSE -eq 1 ]; then
+    echo -e "Error : $@" 1>&2
   fi
 }
 
@@ -177,15 +175,24 @@ function parseIfaceOutput() {
 ### RULES MGMT
 ### ---
 # Remove all rules in all chains
-function _rules_flush() {
+function _flush_rules() {
   $IPTABLES --table filter --flush
   $IPTABLES --table nat --flush
+  $IPTABLES --table mangle --flush
 }
 # Remove all user defined chains (these what are not built in)
-function _chains_flush() {
+function _flush_chains() {
   $IPTABLES --table filter --delete-chain
   $IPTABLES --table nat --delete-chain
+  $IPTABLES --table mangle --delete-chain
 }
+# Reset all packets counter
+function _reset_counters() {
+  $IPTABLES --table filter --zero
+  $IPTABLES --table nat --zero
+  $IPTABLES --table mangle --zero
+}
+
 
 ### ---
 ### GLOBAL POLICIES
@@ -199,9 +206,9 @@ function _policy {
     $IPTABLES --table filter --policy OUTPUT ACCEPT
 
     if [ $IF_IPV4_FORWARD -eq 1 ]; then
-      $IPTABLES -t filter -P FORWARD ACCEPT
+      $IPTABLES --table filter -P FORWARD ACCEPT
     else
-      $IPTABLES -t filter -P FORWARD DROP
+      $IPTABLES --table filter -P FORWARD DROP
     fi
 
     # NAT
@@ -225,7 +232,17 @@ function _policy {
 # @param[string] : the name of the table in which to load the rules
 #        INPUT OUTPUT FORWARD
 # @param[string] : the configuration string from configuration file
-function _load_rules() {
+# @return[int] : 0 if all rule are correctly set
+#                X  the iptables return code
+#                100 if an input rule is declare with a output interface
+#                101 if an output rule is declare with a input interface
+#                102 if a single interface is given for FORWARD table
+#                103 if the table name is not in INPUT, OUTPUT, FORWARD
+function _load_filter_rules() {
+  # bad table name
+  if [[ ! $1 =~ ^INPUT|OUTPUT|FORWARD$ ]]; then
+    return 103
+  fi
   # Loop for each rule (separated by space)
   for entry in $2; do
     _debug "reading config entry : $entry"
@@ -238,7 +255,7 @@ function _load_rules() {
     local out_iface=
     # Loop for each command (separated by F_SEP, pipe as default)
     for c in ${entry//${F_SEP}/ }; do
-      # partial port (dst only) matching
+      # PARTIAL PORT (dst only) matching
       if [[ "$c" =~ ^${E_REG_PROTO}${C_SEP}${E_REG_RANGE}$ ]]; then
         _debug "  => proto+port : $c"
         protocol=$(parseProtocol "$c")
@@ -249,7 +266,7 @@ function _load_rules() {
         if [[ -n $dst_port ]]; then
           dst_port="--destination-port $dst_port"
         fi
-      # full port (dst+src) matching
+      # FULL PORT (dst+src) matching
       elif [[ "$c" =~ ^${E_REG_PROTO}${C_SEP}${E_REG_RANGE}${C_SEP}${E_REG_RANGE}$ ]]; then
         _debug "  => proto+port+port : $c"
         protocol=$(parseProtocol "$c")
@@ -264,7 +281,7 @@ function _load_rules() {
         if [[ -n $dst_port ]]; then
           dst_port="--destination-port $dst_port"
         fi
-      # src address matching
+      # SOURCE ADDRESS matching
       elif [[ "$c" =~ ^${E_REG_SRC}${C_SEP}${E_REG_IPV4}$ ]]; then
         _debug "  => src addr : $c"
         src_address=$(parseAddress "$c")
@@ -273,7 +290,7 @@ function _load_rules() {
         else
           src_address=
         fi
-      # dst address matching
+      # DESTINATION ADDRESS matching
       elif [[ "$c" =~ ^${E_REG_DST}${C_SEP}${E_REG_IPV4}$ ]]; then
         _debug "  => dst addr : $c"
         dst_address=$(parseAddress "$c")
@@ -282,62 +299,112 @@ function _load_rules() {
         else
           dst_address=
         fi
-      # iface reading matching
+      # SINGLE INTERFACE matching
+      elif [[ "$c" =~ ^${E_REG_IFACE}$ ]]; then
+        _debug "  => iface : $c"
+        
+        # interface
+        iface=$(parseIfaceInput "$c")
+        if [[ -n $iface ]]; then
+          # error during forward rule with an unique interface
+          if [[ $1 = 'FORWARD' ]]; then
+            _error "single interface in FORWARD table (ambiguous rules) '$entry'"
+            return 102
+          elif [[ "$1" = 'INPUT' ]]; then
+            in_iface="--in-interface $iface"
+          elif [[ "$1" = 'OUTPUT' ]]; then
+            out_iface="--out-interface $iface"
+          fi
+        else
+          in_iface=
+          out_iface=
+        fi  
+      
+      # IN/OUT INTERFACE matching
       elif [[ "$c" =~ ^${E_REG_IFACE}${C_SEP}${E_REG_IFACE}$ ]]; then
         _debug "  => iface+iface : $c"
+        
+        # input interface
         in_iface=$(parseIfaceInput "$c")
         if [[ -n $in_iface ]]; then
+          # error during output rule with an input interface
+          if [[ $1 = 'OUTPUT' ]]; then
+            _error "input interface in OUTPUT table '$entry'"
+            return 101
+          fi
           in_iface="--in-interface $in_iface"
         else
           in_iface=
         fi
+        
+        # output interface
         out_iface=$(parseIfaceOutput "$c")
         if [[ -n $out_iface && $out_iface != '*' ]]; then
+          # error during input rule with an output interface
+          if [[ $1 = 'INPUT' ]]; then
+            _error "output interface in INPUT table '$entry'"
+            return 100
+          fi
           out_iface="--out-interface $out_iface"
         else
           out_iface=
         fi
       else
-        _debug "  # error : $c"
+        _error "error reading line : $entry"
       fi
     done
-    _echo "$IPTABLES --table filter --append $1 $in_iface $out_iface $src_address $dst_address $protocol $src_port $dst_port"
-    
+    _echo --table filter --append $1 $in_iface $out_iface $src_address $dst_address $protocol $src_port $dst_port
+    $IPTABLES --table filter --append $1 $in_iface $out_iface $src_address $dst_address $protocol $src_port $dst_port
+    result=$?
+    if [[ $result -ne 0 ]]; then
+      return $result
+    fi
   done
+  return 0
+}
+
+
+function _load_anti_ddos_rules() {
+  $IPTABLES --table filter --new-chain DDOS_PROTECT
+  
 }
 
 
 
+###### RUNNING ######
+IS_VERBOSE=1
+
 # Load global configuration
-[ -r $IPTABLES_CONFIG ] && source $IPTABLES_CONFIG
+[[ -r $IPTABLES_CONFIG ]] && source $IPTABLES_CONFIG
 
-# Load the VERBOSE setting and other rcS variables
-#source /lib/init/vars.sh
-
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
-# and status_of_proc is working.
-#source /lib/lsb/init-functions
-
-# Exit if the iptables is not installed
-if ! [ -x "$IPTABLES" ]; then
-  exit 0
+# Exit if the iptables command is not available
+if [[ ! -x "$IPTABLES" ]]; then
+  _error "The iptables command is the path or not installed"
+   #exit 1
 fi
 
 # Exit if the config have not been sourced
-if [ -z "$IF_CONFIG_SOURCED" ]; then
-  log_failure_msg "$DESC: Local 'config' file not sourced. Check the '$IPTABLES_CONFIG' path."
-  exit 1
+if [[ -z "$IF_CONFIG_SOURCED" ]]; then
+  _error "The configuration file have not been source or is not readable"
+  #exit 2
 fi
 
 
-IS_VERBOSE=1
+
+
+_load_filter_rules 'INPUT' "$INPUT"
+result=$?
+if [[ $? -ne 0 ]]; then exit $?; fi
+_load_filter_rules 'OUTPUT' "$OUTPUT"
+result=$?
+if [[ $? -ne 0 ]]; then exit $?; fi
+_load_filter_rules 'FORWARD' "$FORWARD"
+result=$?
+if [[ $? -ne 0 ]]; then exit $?; fi
 
 
 
-_load_rules 'INPUT' "$FORWARDED"
-exit 0
-
+exit 
 ###############################
 ###############################
 # DO NOT READ UNDER THIS LINE #
@@ -353,163 +420,6 @@ exit 0
 
 
 
-
-
-###########################
-# Start the Firewall rules
-###########################
-# Start function, it setup all firewall rules according to configuration
-# @return[int] : 0 if rules have been correctly set
-#          2 if rules could not be set
-function do_start() {
-  _flush_all_rules
-  _flush_all_chains
-  _set_close_policy
-  #_set_packet_rules
-  if [ $? -ne 0 ]; then
-  	return 2
-  fi
-
-  _allow_connection_state
-  _allow_input_output_icmp
-
-  if [ -n "$NETWORK_LOOPBACK" ]; then
-  	_allow_loopback_interface
-  fi
-
-  _allow_input_output_service_for_all
-
-  if [ -n "$NETWORK_ETH0" ]; then
-  	_allow_input_output_service_for_eth0
-  fi
-  if [ -n "$NETWORK_WLAN0" ]; then
-  	_allow_input_output_service_for_wlan0
-  fi
-  if [ -n "$NETWORK_VPN" ]; then
-  	_allow_input_output_service_for_vpn
-  fi
-  if [ -n "$NETWORK_ETH0_ALT" ]; then
-  	_allow_input_output_service_for_eth0_0
-  fi
-
-  if [ "$IF_IPV4_FORWARD" -eq 1 ]; then
-  	_allow_routing_icmp
-  	_allow_routing_service
-  	_setup_nat_masquerading
-  fi
-}
-
-##########################
-# Stop the Firewall rules
-##########################
-
-# Remove all rules of the firewall, turn it open policy
-# return[int] : 0 if rules have been correctly remove
-#               2 if rules could not be remove
-function do_stop() {
-  _set_open_policy
-  if [ $? -ne 0 ]; then
-  	return 2
-  fi
-
-  _flush_all_rules
-  _flush_all_chains
-}
-
-##########################
-# Restart the Firewall rules
-##########################
-
-# Restart all rules of the firewall
-# return :	0 if rules have been correctly remove
-#			2 if firewall failed to start
-#			3 if firewall failed to stop
-function do_restart() {
-  _do_stop 2>/dev/null
-  case $? in
-  0|1)
-  # stop success, now run start
-  	_do_start 2>/dev/null
-  	case $? in
-  	# Start sucess
-  	0|1)	return 0;;
-  	# Failed to start
-  	*)	return 2;;
-  	esac
-  	;;
-  # Failed to stop
-  *)	return 3;;
-  esac
-}
-
-##########################
-# Test the Firewall rules
-##########################
-
-# Save all firewall rules in a file
-# param[in] : OPTIONNAL the path of the file to write the firewall rules
-# return :	0 if rules have been correctly saved
-#			2 if save failed
-function do_save() {
-  local dest_file="$1"
-  if [ -z "$1" ]; then
-  	dest_file=${IPTABLES_BACKUP_FILE}
-  fi
-  hash iptables-save 2>/dev/null 1>&2
-  if [ $? -ne 0 ]; then
-  	return 2
-  fi
-
-  /sbin/iptables-save > ${dest_file}
-}
-
-# Restore all firewall rules from a file
-# return :	0 if rules have been correctly restored
-#			2 if restore failed
-function do_restore() {
-  hash iptables-restore 2>/dev/null 1>&2
-  if [ $? -ne 0 ]; then
-  	return 2
-  fi
-
-  if [ -f "${IPTABLES_BACKUP_FILE}" ]; then
-  	/sbin/iptables-restore < ${IPTABLES_BACKUP_FILE}
-  fi
-}
-
-# Apply new firewall rules and wait for an user confirmation before saving them
-# return :	0 if rules have been correctly set
-#			2 if applying failed
-function do_test() {
-  log_action_msg 'Saving current firewall rules'
-  _do_save
-  if [ $? -ne 0 ]; then
-  	log_failure_msg 'Unable to save current rules'
-  	return 2
-  fi
-
-  log_warning_msg 'Be careful that the caracters are put to screen after you typed them to ensure a bi-directionnal communication'
-  log_warning_msg "Previous configuration will be restore in ${TIMEOUT_FOR_TEST} seconds if no action is performed. Type 'OK' apply new rules [wait for ${TIMEOUT_FOR_TEST}s]"
-  log_action_msg 'Testing and applying new rules'
-  _do_restart
-
-  read -t "${TIMEOUT_FOR_TEST}" -n 2 input
-  echo "$input" | grep --ignore-case 'ok' >/dev/null 2>&1
-  if [ $? -eq 0 ]; then
-  	log_success_msg 'Saving new rules'
-  else
-  	local debug_file="/tmp/iptables_$(date +%Y-%m-%d_%H-%M)"
-  	_do_save "$debug_file"
-  	log_warning_msg "A snapshot of the new firewall rules have been save to $debug_file"
-  	_do_restore
-  	if [ $? -ne 0 ]; then
-  		log_failure_msg 'Unable to restore current rules'
-  		return 2
-  	fi
-  	log_failure_msg 'Old rules have been restored'
-  	return 2
-  fi
-}
 
 
 
